modules:
    collection:
        root: $PROJECT_DIR$
        excluded:
            - .idea
        sources:
            - .
        tests:
            - Tests
        libraries:
            - vendor
servers:
    aircury:
        host: aircury.local
        mappings:
            $PROJECT_DIR$: /var/www/aircury/src/collection
deployment:
    collection:
        type: SFTP
        host: aircury.local
        url: http://aircury.local
        port: 2222
        private_key: env(PRIVATE_KEY_PATH)
        mappings:
            $PROJECT_DIR$: /var/www/aircury/src/collection
            $PROJECT_DIR$/../..: /var/www/aircury
php:
    language_level: 7.1
    xdebug:
        port: env(XDEBUG_REMOTE_PORT)
    interpreters:
        Remote PHP - collection:
            type: SSH
            username: www-data
            host: aircury.local
            port: 2222
            php_path: /usr/bin/php
            private_key: env(PRIVATE_KEY_PATH)
            phpunit:
                configuration: phpunit.xml.dist
                loader: vendor/autoload.php
vcs:
    $PROJECT_DIR$/../..: Git
symfony: ~
run:
    Tests:
        type: PHPUnit
        folder: Tests
    aircury:configure:ide collection:
        type: PHP Console
        script: ../../bin/console
        parameters: aircury:configure:ide src/Collection -v
        environment:
            PRIVATE_KEY_PATH: env(PRIVATE_KEY_PATH)
            XDEBUG_REMOTE_PORT: env(XDEBUG_REMOTE_PORT)
